title: "Pill"
status: "ready"

context:
  pills:
    - message: Pill Example
    - message: Example item with a lot more text
    - message: Meta item

variants:
  - name: Secondary
    context:
      pills:
        - message: Pill Example
          modifier: pill--secondary
        - message: Example item with a lot more text
          modifier: pill--secondary
        - message: Secondary meta
          modifier: pill--secondary
  - name: Grey
    context:
      pills:
        - message: Pill Example
          modifier: pill--grey
        - message: Example item with a lot more text
          modifier: pill--grey
        - message: Grey meta
          modifier: pill--grey
