title: "Links"
status: "ready"

context:
  link:
    message: This is a standard link item

variants:
  -
    name: plain
    context:
      link:
        modifier: link--plain
        message: This is a plain link item
  -
    name: block
    context:
      link:
        modifier: link--block
        message: This is a display block link item
  -
    name: fancy
    context:
      link:
        modifier: link--fancy
        message: This is a fancy link item
  -
    name: white
    context:
      link:
        modifier: link--white
        message: This is a white link item
