title: "Blockquote"
status: "ready"

context:
  blockquote:
    message: >-
      This is a blockquote message lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem massa, facilisis a nibh quis, iaculis feugiat felis. Duis tellus libero, faucibus quis tincidunt id, dictum vel nisl. Donec lorem sem, consequat vitae maximus non, placerat eu quam.
