title: "Meta"
status: "ready"

context:
  meta:
    message: Meta Text

variants:
  -
    name: featured
    context:
      meta:
        message: Meta Text (Featured)
        modifier: meta--featured
  -
    name: highlight
    context:
      meta:
        message: Meta Text (Highlight)
        modifier: meta--highlight
  -
    name: tight
    context:
      meta:
        message: Meta Text (Tight)
        modifier: meta--tight
  -
    name: grey
    context:
      meta:
        message: Meta Text (Grey)
        modifier: meta--grey
